"""Ceilometer summary and QC plots (P014).

    python scripts/ceilometer_summary.py [--plot-days 2022-06-01 ... ]

Reads every CHM15k day file for CDLRA and CDLRB, writes per-day statistics to data/ceilometer_days.parquet
(ignored) and docs/data/ceilometer_summary.md (committed), and time-height plots for selected days to
docs/data/figures/ for visual comparison with the vendor plots shipped with Eye2Sky.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from stratia.data.ceilometer import read_backscatter, read_chm15k  # noqa: E402
from stratia.data.registry import load_paths  # noqa: E402

BINS_KM = [0, 1, 2, 4, 8, 12]


def day_stats(df: pd.DataFrame) -> dict:
    c1 = df.cbh1
    return {"records": len(df), "cloud_frac": c1.notna().mean(), "cbh1_median_m": c1.median(),
            "multilayer_frac": (df.n_layers >= 2).mean(), "rain_frac": df.qc_rain.mean(),
            "laser_warn_frac": df.qc_laser_warning.mean(),
            "window_frac": df.qc_window.mean(), "optics_low_frac": df.qc_optics.mean(), "error_frac": df.qc_error.mean()}


def plot_day(path: Path, out: Path, title: str) -> None:
    t, rng, beta = read_backscatter(path)
    df = read_chm15k(path)
    keep = rng <= 12000
    fig, ax = plt.subplots(figsize=(10, 3.6), dpi=72)
    data = np.log10(np.clip(beta[:, keep].T, 1e3, None))
    ax.pcolormesh(t, rng[keep] / 1000, data, shading="auto", cmap="viridis", vmin=4, vmax=7, rasterized=True)
    for k, col in zip(range(1, 4), ["red", "orange", "white"], strict=True):
        ax.plot(df.index, df[f"cbh{k}"] / 1000, ".", ms=1.2, color=col, label=f"cbh layer {k}")
    ax.set(ylabel="height above instrument (km)", title=title, ylim=(0, 12))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    ax.legend(loc="upper right", markerscale=6, fontsize=8)
    fig.tight_layout()
    fig.savefig(out)
    plt.close(fig)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--plot-days", nargs="*", default=["2022-06-01"])
    ap.add_argument("--md", default="docs/data/ceilometer_summary.md")
    a = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    base = Path(load_paths()["data_root"]) / "Eye2Sky" / "ceilometer" / "ceil" / "data"
    rows, cbh_all = [], {}
    for code in ("CDLRA", "CDLRB"):
        heights = []
        for f in sorted((base / code).glob("*.nc")):
            df = read_chm15k(f)
            rows.append({"ceilometer": code, "day": f.name[:8], **day_stats(df)})
            ok = df[~df.qc_any & df.cbh1.notna()]
            heights.append(ok.cbh1.to_numpy())
        cbh_all[code] = np.concatenate(heights) if heights else np.array([])
    days = pd.DataFrame(rows)
    Path("data").mkdir(exist_ok=True)
    days.to_parquet("data/ceilometer_days.parquet", index=False)

    L = ["# Ceilometer summary (CHM15k, Eye2Sky)", "", "Generated by `scripts/ceilometer_summary.py` (P014). "
         "Heights are metres above the instrument; statistics over all records, CBH climatology over records "
         "without any QC flag.", "", "| Ceilometer | Days | Records | Cloud (lowest layer present) | Median lowest CBH (m) "
         "| ≥ 2 layers | Rain | Particles on window | Optics < 50 % | Error bits | Laser warning (0x8000) |",
         "|---|---|---|---|---|---|---|---|---|---|---|"]
    for code, g in days.groupby("ceilometer"):
        w = g.records
        wavg = lambda col, w=w, g=g: (g[col] * w).sum() / w.sum()  # noqa: E731
        L.append(f"| {code} | {len(g)} | {int(w.sum()):,} | {wavg('cloud_frac'):.1%} | {np.median(cbh_all[code]):.0f} | "
                 f"{wavg('multilayer_frac'):.1%} | {wavg('rain_frac'):.1%} | {wavg('window_frac'):.1%} | "
                 f"{wavg('optics_low_frac'):.1%} | {wavg('error_frac'):.1%} | {wavg('laser_warn_frac'):.1%} |")
    L += ["", "## Lowest-cloud-base climatology (QC-clean records)", "",
          "| Ceilometer | " + " | ".join(f"{lo}–{hi} km" for lo, hi in zip(BINS_KM[:-1], BINS_KM[1:], strict=True)) + " |",
          "|---|" + "---|" * (len(BINS_KM) - 1)]
    for code, h in cbh_all.items():
        hist, _ = np.histogram(h / 1000, bins=BINS_KM)
        L.append(f"| {code} | " + " | ".join(f"{x / max(hist.sum(), 1):.1%}" for x in hist) + " |")
    fig_dir = Path("docs/data/figures")
    fig_dir.mkdir(parents=True, exist_ok=True)
    for day in a.plot_days:
        d = day.replace("-", "")
        for code in ("CDLRA", "CDLRB"):
            f = next((base / code).glob(f"{d}_*.nc"), None)
            if f is not None:
                out = fig_dir / f"ceilometer_{code}_{d}.png"
                plot_day(f, out, f"{code} {day} — log10 backscatter with detected cloud bases")
                L += ["", f"![{code} {day}](figures/{out.name})"]
    Path(a.md).write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("\n".join(L[:12]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
