"""Eye2Sky inventory (P012): images per station and day, calibration validity, ceilometer coverage,
and how many image-days can be paired with a ceilometer.

    python scripts/eye2sky_inventory.py [--max-distance-km 1.0] [--md docs/data/eye2sky_inventory.md]

Re-run whenever new Eye2Sky downloads are added to the data root.
"""

from __future__ import annotations

import argparse
import math
import re
import sys
from collections import Counter, defaultdict
from datetime import UTC, date, datetime
from pathlib import Path

import openpyxl
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from stratia.data.registry import load_paths  # noqa: E402

IMG_RE = re.compile(r"^(\d{14})_(\d+)\.jpe?g$", re.I)          # 20220401045530_160.jpg -> UTC time, exposure
CEIL_RE = re.compile(r"^(\d{8})_(CHM\d+)\.nc$")                  # 20220401_CHM180102.nc
CEILOMETERS = {"CDLRA": "Oldenburg", "CDLRB": "Westerstede"}


def haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp, dl = p2 - p1, math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * 6371.0088 * math.asin(math.sqrt(a))


def read_stations(xlsx: Path) -> dict[str, dict]:
    ws = openpyxl.load_workbook(xlsx, read_only=True).active
    rows = list(ws.iter_rows(values_only=True))
    hdr = [str(h).strip() for h in rows[0]]
    out = {}
    for r in rows[1:]:
        if not r or not r[0]:
            continue
        d = dict(zip(hdr, r, strict=False))
        out[str(d["Station ID"]).strip()] = {"type": str(d["Type"]).strip(), "lat": float(d["Latitude"]),
                                             "lon": float(d["Longitude"]), "place": d["Place"]}
    return out


def scan_images(root: Path) -> dict[str, dict]:
    """station -> {day -> {'n': count, 'exposures': Counter}}"""
    per = defaultdict(lambda: defaultdict(lambda: {"n": 0, "exposures": Counter()}))
    for p in (root / "2022").rglob("*.jp*g"):
        m = IMG_RE.match(p.name)
        station = next((part.split("_")[2] for part in p.parts if part.startswith("ASI_")), None)
        if not m or not station:
            continue
        t = datetime.strptime(m.group(1), "%Y%m%d%H%M%S")
        rec = per[station][t.date()]
        rec["n"] += 1
        rec["exposures"][int(m.group(2))] += 1
    return per


def read_calibrations(root: Path) -> dict[str, list[dict]]:
    out = defaultdict(list)
    for y in sorted((root / "asi_meta").glob("*/*.yaml")):
        station = y.parent.name
        if y.stat().st_size == 0:
            out[station].append({"file": y.name, "status": "empty file"})
            continue
        try:
            d = yaml.safe_load(y.read_text(encoding="utf-8"))
            out[station].append({"file": y.name, "status": "ok", "mounted": d.get("mounted"),
                                 "demounted": d.get("demounted"), "model": d.get("camera_model")})
        except yaml.YAMLError as e:
            out[station].append({"file": y.name, "status": f"parse error: {type(e).__name__}"})
    return out


def calib_valid_on(cals: list[dict], day: date) -> str | None:
    t = datetime(day.year, day.month, day.day, 12, tzinfo=UTC)
    for c in cals:
        if c["status"] != "ok" or not c.get("mounted"):
            continue
        mo = c["mounted"] if c["mounted"].tzinfo else c["mounted"].replace(tzinfo=UTC)
        de = c.get("demounted")
        de = (de if de.tzinfo else de.replace(tzinfo=UTC)) if de else None
        if mo <= t and (de is None or t < de):
            return c["file"]
    return None


def scan_ceilometers(root: Path) -> dict[str, set[date]]:
    out = {}
    for code in CEILOMETERS:
        days = set()
        for f in (root / "ceilometer" / "ceil" / "data" / code).glob("*.nc"):
            m = CEIL_RE.match(f.name)
            if m:
                days.add(datetime.strptime(m.group(1), "%Y%m%d").date())
        out[code] = days
    return out


def build_report(root: Path, max_km: float) -> tuple[str, dict]:
    stations = read_stations(root / "Eye2Sky_Station_List.xlsx")
    imgs = scan_images(root)
    cals = read_calibrations(root)
    ceil = scan_ceilometers(root)
    near = {c: sorted((haversine_km(stations[c]["lat"], stations[c]["lon"], s["lat"], s["lon"]), sid)
                      for sid, s in stations.items() if sid != c and s["type"] != "CEI") for c in CEILOMETERS}

    L = ["# Eye2Sky inventory", "",
         f"Generated by `scripts/eye2sky_inventory.py` (P012). Pairing radius: {max_km} km.", ""]
    L += ["## Camera images on disk", "",
          "| Station | Days | Images | First day | Last day | Exposure suffixes (count) "
          "| Days with valid calibration |", "|---|---|---|---|---|---|---|"]
    total_imgs = 0
    for st in sorted(imgs):
        days = sorted(imgs[st])
        n = sum(v["n"] for v in imgs[st].values())
        total_imgs += n
        exp = Counter()
        for v in imgs[st].values():
            exp.update(v["exposures"])
        cal_ok = sum(1 for d in days if calib_valid_on(cals.get(st, []), d))
        L.append(f"| {st} | {len(days)} | {n:,} | {days[0]} | {days[-1]} | "
                 f"{', '.join(f'{k}: {v}' for k, v in exp.most_common(4))} | {cal_ok}/{len(days)} |")
    L += ["", f"Total: {total_imgs:,} images.", ""]

    L += ["## Ceilometers", "", "| Ceilometer | Site | Days of data | First | Last | Camera stations within "
          f"{max_km} km (distance) |", "|---|---|---|---|---|---|"]
    for c, site in CEILOMETERS.items():
        d = sorted(ceil[c])
        close = [f"{sid} ({km:.2f} km)" for km, sid in near[c] if km <= max_km]
        first, last = (d[0], d[-1]) if d else ('-', '-')
        L.append(f"| {c} | {site} | {len(d)} | {first} | {last} | {', '.join(close) or 'none'} |")

    pairs = {}
    L += ["", "## Pairable image-days (camera within radius, ceilometer data that day, valid calibration)", "",
          "| Ceilometer | Station | Pairable days | Images |", "|---|---|---|---|"]
    for c in CEILOMETERS:
        for km, sid in near[c]:
            if km > max_km or sid not in imgs:
                continue
            days = [d for d in imgs[sid] if d in ceil[c] and calib_valid_on(cals.get(sid, []), d)]
            n = sum(imgs[sid][d]["n"] for d in days)
            pairs[(c, sid)] = (len(days), n)
            L.append(f"| {c} | {sid} | {len(days)} | {n:,} |")
    if not pairs:
        L.append("| — | — | 0 | 0 |")
        L += ["", "**No camera images at the ceilometer sites are on disk yet.** Cloud-base-height training needs "
              "images from stations within the radius of CDLRA (Oldenburg) or CDLRB (Westerstede) on ceilometer days."]

    L += ["", "## Calibration files", "", "| Station | File | Status | Valid from | Valid until | Camera model |",
          "|---|---|---|---|---|---|"]
    for st in sorted(cals):
        for c in cals[st]:
            L.append(f"| {st} | {c['file']} | {c['status']} | {c.get('mounted', '')} | {c.get('demounted', '')} "
                     f"| {c.get('model', '')} |")
    L += ["", "## Nearest camera stations to each ceilometer", ""]
    for c in CEILOMETERS:
        L.append(f"- **{c}**: " + ", ".join(f"{sid} {km:.2f} km" for km, sid in near[c][:8]))
    summary = {"images": total_imgs, "stations_with_images": sorted(imgs),
               "pairs": {f"{a}/{b}": v for (a, b), v in pairs.items()},
               "ceilometer_days": {c: len(v) for c, v in ceil.items()}}
    return "\n".join(L) + "\n", summary


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-distance-km", type=float, default=1.0)
    ap.add_argument("--md", default="docs/data/eye2sky_inventory.md")
    a = ap.parse_args()
    root = Path(load_paths()["data_root"]) / "Eye2Sky"
    md, summary = build_report(root, a.max_distance_km)
    Path(a.md).write_text(md, encoding="utf-8", newline="\n")
    print(summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
