"""Inventory of the local data root (P011).

    python scripts/inventory.py [--out data/inventory.parquet] [--md docs/data/inventory.md]

Walks every file under data_root, assigns it to a registered dataset (by folder), reads image headers
(size, mode) without decoding pixels, flags junk (macOS resource forks, zero-byte files), and writes a
per-file Parquet table (git-ignored) plus a Markdown summary (committed).
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pandas as pd
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from stratia.data.registry import IMAGE_EXT, dataset_dirs, load_paths, load_registry  # noqa: E402


def owner_map(reg: dict, root: Path) -> list[tuple[Path, str]]:
    """(folder, dataset) pairs, longest folder first so nested registrations win."""
    pairs = [(p.resolve(), key) for key, d in reg.items() for p in dataset_dirs(d, root).values()]
    return sorted(pairs, key=lambda t: len(str(t[0])), reverse=True)


def describe(path: Path, root: Path, owners: list[tuple[Path, str]]) -> dict:
    rp = path.resolve()
    dataset = next((k for folder, k in owners if rp.is_relative_to(folder)), "unregistered")
    st = path.stat()
    ext = path.suffix.lower()
    rec = {"dataset": dataset, "relpath": path.relative_to(root).as_posix(), "ext": ext, "bytes": st.st_size,
           "junk": "__MACOSX" in path.parts or path.name.startswith("._") or st.st_size == 0,
           "is_image": ext in IMAGE_EXT, "width": None, "height": None, "mode": None, "error": None}
    if rec["is_image"] and not rec["junk"]:
        try:
            with Image.open(path) as im:
                rec["width"], rec["height"], rec["mode"] = im.width, im.height, im.mode
        except Exception as e:  # noqa: BLE001 - corrupt files are recorded, not fatal
            rec["error"] = f"{type(e).__name__}: {e}"[:200]
    return rec


def summarise(df: pd.DataFrame) -> str:
    lines = ["# Data inventory", "",
             f"Generated by `scripts/inventory.py` (P011). Files: {len(df):,}; "
             f"total size {df.bytes.sum() / 1e9:.1f} GB.", "",
             "| Dataset | Files | Images (valid) | Junk | Unreadable | Size GB "
             "| Top resolutions (W×H: count) | Modes | Other file types |",
             "|---|---|---|---|---|---|---|---|---|"]
    for ds, g in df.groupby("dataset"):
        img = g[g.is_image & ~g.junk]
        valid = img[img.error.isna()]
        res = Counter(f"{int(w)}×{int(h)}" for w, h in zip(valid.width, valid.height, strict=True))
        top = ", ".join(f"{k}: {v}" for k, v in res.most_common(3))
        modes = ", ".join(f"{k}: {v}" for k, v in Counter(valid["mode"]).most_common(3))
        other = Counter(g[~g.is_image].ext)
        other_s = ", ".join(f"{k or '(none)'}: {v}" for k, v in other.most_common(5))
        lines.append(f"| {ds} | {len(g):,} | {len(valid):,} | {int(g.junk.sum()):,} | {int(img.error.notna().sum())} | "
                     f"{g.bytes.sum() / 1e9:.2f} | {top} | {modes} | {other_s} |")
    bad = df[df.error.notna()]
    if len(bad):
        lines += ["", "## Unreadable images", ""] + [f"- `{r.relpath}`: {r.error}" for r in bad.head(50).itertuples()]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data/inventory.parquet")
    ap.add_argument("--md", default="docs/data/inventory.md")
    ap.add_argument("--workers", type=int, default=16)
    a = ap.parse_args()
    root = Path(load_paths()["data_root"])
    owners = owner_map(load_registry(), root)
    files = [p for p in root.rglob("*") if p.is_file()]
    with ThreadPoolExecutor(a.workers) as ex:
        rows = list(ex.map(lambda p: describe(p, root, owners), files, chunksize=256))
    df = pd.DataFrame(rows)
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(a.out, index=False)
    Path(a.md).parent.mkdir(parents=True, exist_ok=True)
    Path(a.md).write_text(summarise(df), encoding="utf-8")
    print(summarise(df))
    return 0


if __name__ == "__main__":
    sys.exit(main())
