"""Build Montenegro soft labels and check them against the dataset README (P016).

    python scripts/montenegro_labels.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from stratia.data.montenegro import VARIABLES, load_annotations, load_items, soft_labels  # noqa: E402
from stratia.data.registry import load_paths  # noqa: E402

README_FACTS = {
    "annotations": 11191, "images": 2522, "annotators": 9,
    "raters_per_image": {1: 252, 2: 23, 4: 781, 5: 1277, 6: 11, 7: 108, 8: 68, 9: 2},
    "missing": {"CM": 59, "CH": 56, "CL": 9, "Nh": 5, "altitude_class": 1, "N": 0, "h": 0},
}


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    root = Path(load_paths()["data_root"]) / "Montenegro"
    items, ann = load_items(root), load_annotations(root)
    soft = soft_labels(ann).merge(items, on="item_id", how="left")
    checks = {
        "annotations": (len(ann), README_FACTS["annotations"]),
        "images": (soft.item_id.nunique(), README_FACTS["images"]),
        "annotators": (ann.user_id.nunique(), README_FACTS["annotators"]),
        "raters_per_image": (soft.n_raters.value_counts().sort_index().to_dict(), README_FACTS["raters_per_image"]),
        "missing": ({c: int(ann[c].isna().sum()) for c in VARIABLES.values()}, README_FACTS["missing"]),
        "images_with_file_on_disk": (int(sum((root / f).exists() for f in soft.image_file)), README_FACTS["images"]),
        "unique_pairs": (int(ann.duplicated(["item_id", "user_id"]).sum()), 0),
    }
    ok = all(got == want for got, want in checks.values())
    Path("data").mkdir(exist_ok=True)
    soft.to_parquet("data/montenegro_soft_labels.parquet", index=False)

    L = ["# Montenegro labels", "", "Generated by `scripts/montenegro_labels.py` (P016).", "",
         "## Checks against the dataset README", "", "| Check | Parsed | README | OK |", "|---|---|---|---|"]
    for k, (got, want) in checks.items():
        L.append(f"| {k} | {got} | {want} | {'yes' if got == want else '**NO**'} |")
    L += ["", "## Per-variable answers and majority agreement", "",
          "| Variable | Answers | Distinct codes | Most common codes | Mean majority share (images with ≥ 4 raters) |",
          "|---|---|---|---|---|"]
    multi = soft[soft.n_raters >= 4]
    for c in VARIABLES.values():
        vc = ann[c].value_counts()
        top = ", ".join(f"{k}: {v}" for k, v in vc.head(4).items())
        L.append(f"| {c} | {int(ann[c].notna().sum()):,} | {len(vc)} | {top} | {multi[f'{c}_agreement'].mean():.3f} |")
    L += ["", f"Days: {soft.day.nunique()} ({soft.day.min()} to {soft.day.max()}). "
          "Majority share = fraction of raters choosing the most common code; a simple agreement indicator "
          "(chance-corrected agreement, Krippendorff's α, follows in P035)."]
    Path("docs/data/montenegro_labels.md").write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print("\n".join(L))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
