"""Verify segmentation label encodings and write QA sheets (P018).

    python scripts/segmentation_qa.py

For every dataset: all image/mask pairs exist and match in size; class pixel shares; a physics check of the
encoding (daytime clear sky must have a higher blue/red ratio than cloud); an overlay sheet of 8 samples.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from stratia.data.registry import load_paths  # noqa: E402
from stratia.data.segmentation import CLOUD, IGNORE, SKY, SKY_INVALID, build_index, load_masks  # noqa: E402

SKY_COLOURS = {SKY_INVALID: (90, 90, 90), SKY: (40, 120, 255), CLOUD: (255, 150, 0)}
LAYER_COLOURS = {0: (230, 40, 40), 1: (250, 220, 0), 2: (0, 230, 230)}


def overlay(img: Image.Image, sky: np.ndarray, layer: np.ndarray, size: int = 220) -> Image.Image:
    base = np.array(img.convert("RGB").resize((size, size)), dtype=float)
    lab = np.array(Image.fromarray(sky).resize((size, size), Image.NEAREST))
    lay = np.array(Image.fromarray(layer).resize((size, size), Image.NEAREST))
    out = base.copy()
    for v, c in SKY_COLOURS.items():
        out[lab == v] = 0.55 * base[lab == v] + 0.45 * np.array(c)
    for v, c in LAYER_COLOURS.items():
        out[lay == v] = 0.4 * base[lay == v] + 0.6 * np.array(c)
    return Image.fromarray(out.astype(np.uint8))


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    root = Path(load_paths()["data_root"])
    idx = build_index(root)
    fig_dir = Path("docs/data/figures")
    fig_dir.mkdir(parents=True, exist_ok=True)
    L = ["# Segmentation datasets QA", "", "Generated by `scripts/segmentation_qa.py` (P018). Shares are over all pixels "
         "of 40 sampled masks per dataset; B/R = mean blue/red ratio of the image pixels in each class.", "",
         "| Dataset | Pairs | Splits | Missing masks | Size mismatches | Invalid | Sky | Cloud | Ignore "
         "| B/R sky | B/R cloud | Encoding check |", "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    ok_all = True
    rng = np.random.default_rng(0)
    for ds, g in idx.groupby("dataset", sort=False):
        missing = int((~g.mask_file.map(lambda f: (root / f).exists())).sum())
        sample = g.iloc[rng.choice(len(g), min(40, len(g)), replace=False)]
        shares, br_sky, br_cloud, mismatch = np.zeros(4), [], [], 0
        tiles = []
        for i, r in enumerate(sample.itertuples()):
            img = Image.open(root / r.image_file)
            sky, layer = load_masks(ds, root / r.mask_file)
            if img.size != (sky.shape[1], sky.shape[0]):
                mismatch += 1
                continue
            px = np.array(img.convert("RGB"), dtype=float)
            ratio = px[..., 2] / (px[..., 0] + 1.0)
            for k, v in enumerate((SKY_INVALID, SKY, CLOUD, IGNORE)):
                shares[k] += (sky == v).mean()
            if (sky == SKY).any():
                br_sky.append(ratio[sky == SKY].mean())
            if (sky == CLOUD).any():
                br_cloud.append(ratio[sky == CLOUD].mean())
            if i < 8:
                tiles.append(overlay(img, sky, layer))
        shares /= max(len(sample) - mismatch, 1)
        bs, bc = float(np.mean(br_sky)), float(np.mean(br_cloud))
        night = ds == "swinseg"
        check = "skipped (night: colour prior not applicable)" if night else ("pass" if bs > bc else "**FAIL**")
        ok_all &= (missing == 0 and mismatch == 0 and (night or bs > bc))
        splits = ", ".join(f"{k}: {v}" for k, v in g.split.value_counts().items())
        L.append(f"| {ds} | {len(g):,} | {splits} | {missing} | {mismatch} | {shares[0]:.1%} | {shares[1]:.1%} | "
                 f"{shares[2]:.1%} | {shares[3]:.1%} | {bs:.2f} | {bc:.2f} | {check} |")
        sheet = Image.new("RGB", (220 * 4, 220 * 2 + 18), "white")
        for k, t in enumerate(tiles):
            sheet.paste(t, (220 * (k % 4), 18 + 220 * (k // 4)))
        ImageDraw.Draw(sheet).text((4, 3), f"{ds}: blue = sky, orange = cloud, grey = invalid; layers red/yellow/cyan = "
                                           "low/mid/high", fill="black")
        out = fig_dir / f"qa_seg_{ds}.jpg"
        sheet.save(out, quality=82)
    L += ["", "QA sheets: " + ", ".join(f"[{d}](figures/qa_seg_{d}.jpg)" for d in idx.dataset.unique())]
    Path("docs/data/segmentation_qa.md").write_text("\n".join(x for x in L if x is not None) + "\n", encoding="utf-8",
                                                    newline="\n")
    Path("data").mkdir(exist_ok=True)
    idx.to_parquet("data/segmentation_index.parquet", index=False)
    print("\n".join(L))
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
